### ISSUE TITLE
I'm experiencing crashes on load

### ISSUE THREAD

**Issue by calebmeyer** [kieranju/accents-ui#2]
[Enter steps to reproduce below:]
1. Set the Accents UI theme (any background color)
2. View > Reload (or restart atom)

The only thing which fixes it is deleting accents-ui from my config.cson, which resets atom back to atom dark for syntax and ui.

I really like this theme, and would love to be able to try it out. Let me know if there's anything else I can do to help.

**Atom Version**: 1.0.10
**System**: Mac OS X 10.10.5
**Thrown From**: [accents-ui](https://github.com/kieranju/accents-ui) package, v0.5.0
### Stack Trace

Failed to activate the accents-ui theme

```
At error evaluating function `desaturate`: undefined is not a function in /Users/cm022291/.atom/packages/accents-ui/styles/ui-variables.less:3:29

LessError: error evaluating function `desaturate`: undefined is not a function
  at /Users/cm022291/.atom/packages/accents-ui/styles/ui-variables.less:3:29
```
### Commands

```
     -0:10.3.0 window:update-available (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-ui.theme-atom-dark-syntax)
     -0:07.6.0 settings-view:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-mustache",
      "linter-haml",
      "deprecation-cop",
      "overrides",
      "autocomplete-paths",
      "linter-foodcritic",
      "linter-less",
      "line-ending-selector"
    ],
    "themes": [
      "accents-ui",
      "atom-dark-syntax"
    ]
  },
  "accents-ui": {
    "accentColor": {
      "red": 13,
      "green": 143,
      "blue": 243,
      "alpha": 1
    }
  }
}
```
### Installed Packages

``` coffee
# User
atom-jasmine, v0.6.0
auto-update-packages, v1.0.0
file-icons, v1.6.9
highlight-line, v0.11.0
language-diff, v0.3.1
language-gitignore, v0.2.0
language-haml, v0.21.0
language-lisp, v0.1.2
language-log, v0.6.0
language-restructuredtext, v0.9.0
language-rspec, v0.3.0
language-rust, v0.4.4
linter, v1.5.1
minimap, v4.13.3
minimap-autohide, v0.10.1
minimap-git-diff, v4.1.8
omni-ruler, v0.4.2
open-recent, v2.3.0
pain-split, v1.4.0
set-syntax, v0.3.0
trailing-spaces, v0.3.2
vim-mode, v0.60.0

# Dev
No dev packages
```

**Comment by kieranju** [comment]
Thanks for submitting an issue!

I have to say though, this is quite strange -- I feel like something might be acting unexpectedly on OS X, or your system in general. Hopefully you can help me look into it for a fix! I can't seem to replicate it, but have a hunch where the issue might be occurring.

By default, there's a .less file which holds one variable: `@accent-color: #24d9b0;` 
This is in the ui-accent.less file, under `/accents-ui/styles/`

That's the default red accent colour the theme is set up with. When you change the accent colour, it puts an RGBA value in the config which must then be converted into a Hex value, and then inserted into the ui-accent.less file as shown above.

---

I feel like that conversion is where it's having issues (hopefully how I explained it makes sense)! 

**To help resolve this issue, I've just added a debug option into the theme.** You don't need to reload the theme for the debug mode to start working. Here are some steps to take:
- Clear out any config options for this theme (you've had to do this to get atom running without crashing)
- Update to the latest published version of accents-ui (should be v0.6.0)
- Navigate to the theme settings, where you can change the Accent Colour, and turn on Debug Mode
- Press `Alt + Ctrl + I` or look under `View -> Developer -> Toggle Developer Tools`
- Select the `Console` tab in the developer tools, next to Resources and Audits
- _And finally,_ change the accent colour to anything of your choosing

The console should show three lines once you've picked a random colour, for me it shows:

> accents-ui :: accent colour object : [object Object]
> accents-ui :: accent colour toHexString : #52ab7a
> Color

where Color is the colour object returned from the config file. _I suspect it might log an error._ It would be great if you could just copy and past those three lines for me!

Really hope this isn't too much to ask for – I can't seem to replicate the issue on my machine. Thanks again!

**Comment by calebmeyer** [comment]
Thank you so much for the quick response! The Apple color picker is terrible, has no option to directly enter hex or RGB color codes whatsoever. Here is the console statement logged when I choose a color using it:
![screen shot 2015-09-10 at 8 40 50 am](https://cloud.githubusercontent.com/assets/3342777/9789770/ae09c804-5797-11e5-8f0f-bcbf63094406.png)

It appears that the color picker doesn't output correctly formatted colors. Would it be possible to add a text input next to the accent color option (in addition to the picker) that you can enter hex values into?

Also, here's the configuration in my config.cson:

``` cson
  "accents-ui":
    accentColor:
      red: 13
      green: 143
      blue: 243
      alpha: 1
    debugMode: true
```

**Comment by kieranju** [comment]
Oh wow! So actually that does somewhat solve the problem, or at least provides insight into what the issue was. I'm pretty sure there are better native colour pickers, but Atom doesn't use it :(

Anyway, what's happening is that on your system (for some reason), when converting the RGBA value to Hex, is that it's using shorthand... _and the LESS desaturate function doesn't like that, apparently_

For now, I'm going to manually convert it instead of relying on the function that's already there. And I'll also look into adding a text input so you can manually insert Hex, as I know the default colour picker is quite lacklustre!

Hopefully this'll get you up and running on the theme with no issues, I really appreciate the help ironing this out! You should see a new version to upgrade to soon.

**Comment by kieranju** [comment]
Another quick update, I got the hex input working in conjunction with the standard colour picker!

I've published a major update, as I believe the theme should be in quite a good working order now. Let me know if you continue to run into issues :)

**Comment by calebmeyer** [comment]
I used the new hex input, works great! Thanks for the support on this, this theme looks awesome!

<img width="876" alt="screen shot 2015-09-10 at 8 45 42 pm" src="https://cloud.githubusercontent.com/assets/3342777/9805278/f86ad306-57fc-11e5-93bc-dffed029632d.png">

**Comment by kieranju** [comment]
Thanks a bunch, glad you like it! :+1:
