### ISSUE TITLE
Font-size

### ISSUE THREAD

**Issue by sfarmani** [kieranju/accents-ui#3]
I really like this UI, however the font-sizes for the tabs are too small. I tried going to ui-variables.less and changed font-size but that didn't change the tabs. it only changed the file menu's font. How do I change the tabs.

Also it would actually be nice if you added a setting where people can change the font size of the menu/tabs easier.

**Comment by kieranju** [comment]
My bad, sorry it took so long to reply here!

I've just pushed an update to the theme that adjusts the font sizes to make them a bit more consistent (as you mentioned, the tab's fonts were a bit smaller than they needed to be).

Additionally, you'll see an extra option in the configuration to change the font size used by the entire theme -- at the moment this includes most/all panes (including the configuration pane), tabs, tree-view, and the gutter. It's a bit finicky and can take a few reloads of atom before the font size is applied properly.

When time permits, I'd like to split up the configuration so you can fine tune font sizes across all major portions of the theme :+1:

**Comment by sfarmani** [comment]
cool! Thank you very much!

**Comment by sfarmani** [comment]
Nevermind its working now, Im sorta new to Atom and forgot to Reload :P

**Comment by kieranju** [comment]
No problem!

Supposedly there's a way to get atom to reload its styles through code without doing a full reload, but I wasn't able to get that sorted out :cry:
