### ISSUE TITLE
Support for seti-icons?

### ISSUE THREAD

**Issue by tcoulter** [kieranju/accents-ui#6]
Love this theme. Looks like it doesn't support custom icons (see screenshot). Is there any way to support this? Alternatively, is this seti-icons issue? 

Thanks!

<img width="834" alt="screen shot 2016-05-25 at 10 36 48 am" src="https://cloud.githubusercontent.com/assets/92629/15550106/b868dc0c-2264-11e6-9110-2b387a8bd234.png">

**Comment by tcoulter** [comment]
Closing. Looks like this is likely an issue with seti-icons. Found a similar package that does the trick: https://atom.io/packages/front-icons

**Comment by kieranju** [comment]
Ah, good find! I think you were initially on the right track, it's more or less an issue with accents-ui. Whatever styles seti-icons uses to align the icons doesn't work well with the adjustments I've made to the tabs. 

[front-icons](https://atom.io/packages/front-icons) and [file-type-icons](https://atom.io/packages/file-type-icons) both work well, though!

I'll leave this issue open for the time being to see if I can fix seti-icons for use, as they're used by quite a few people.

**Comment by kieranju** [comment]
It's been a long time standing, but I've been completely re-creating this theme from scratch (see experimental branch) using relative units. In the process of this, icons are better supported, but seti-icons were clearly designed for use with their own theme: seti-ui.

I will likely provide a snippet of CSS to use that corrects them.
