### ISSUE TITLE
border-left for the panes

### ISSUE THREAD

**Issue by dukio** [kieranju/accents-ui#8]
Today I switched from sublime to atom and I choosed this theme because I think it looks amazing!
...but I have noticed that, if you use multiple panes, there's nothing to show where one pane ends and another one start ...

I'll explain better with a before and after image comparsion:
Before: http://i.imgur.com/uOrNkQR.png
After: http://i.imgur.com/K7y6scW.png

CSS Added:
`atom-pane-container atom-pane .item-views { 
    border-left: 1px solid #2D2D2D; 
}`

**Comment by kieranju** [comment]
https://github.com/kieranju/accents-ui/commit/fabe24f84c51a85a3a76a189c0d392ab88f737c7 introduces pane borders to help differentiate them when using multiple panes!

I've opted to use a box-shadow to prevent it from nudging elements around.
